revisi routing, tombol, sama masukin halaman ke bottom navigation, to…
felixfrdd/abank_project pull request #18
Opened 2023-11-20 16:43 UTC by Shinzi04

Tambahin pages ke bottom navigation,
Revisi tombol back di myaccount,
ubah transfer history --> supaya sama navbarnya sama yang lain,
commnand beberapa hal yang gak guna (tolong di cek kalau misalnya bener2 tidak guna bisa dihapus juga)

2023-11-20 17:07 UTC, felixfrdd requested changes

2023-11-20 17:07 UTC, felixfrdd commented on lib/pages/myaccount/change_pin.dart
>            leading: BackButton(
[buildbackbutton](https://github.com/felixfrdd/abank_project/blob/8e0fd1856caaea47b76ba34ea496d8fe1f267210/lib/pages/transfer/new_account_page.dart#L22-L25)
colornya boleh transparent aja seperti di referensi link atas.

2023-11-20 17:07 UTC, felixfrdd commented on lib/pages/myaccount/set_a_limit.dart
>            leading: BackButton(
[buildbackbutton](https://github.com/felixfrdd/abank_project/blob/8e0fd1856caaea47b76ba34ea496d8fe1f267210/lib/pages/transfer/new_account_page.dart#L22-L25)
colornya boleh transparent aja seperti di referensi link atas.

2023-11-20 17:07 UTC, felixfrdd commented on lib/pages/myaccount/view_cvv.dart
>            leading: BackButton(
[buildbackbutton](https://github.com/felixfrdd/abank_project/blob/8e0fd1856caaea47b76ba34ea496d8fe1f267210/lib/pages/transfer/new_account_page.dart#L22-L25)
colornya boleh transparent aja seperti di referensi link atas.

2023-11-29 07:07 UTC, Javier7898 commented on lib/pages/myaccount/set_a_limit.dart
>            leading: BackButton(
tttt

2023-11-29 07:08 UTC, Javier7898 approved these changes
ok 👍

2023-11-29 07:10 UTC, IniGabriel approved these changes
ok

2023-11-29 07:14 UTC, felixfrdd approved these changes

2023-11-29 07:14 UTC, felixfrdd approved these changes
later changes.

2023-11-29 07:14 UTC, merged